# Generated by Django 2.2 on 2019-04-26 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wpFiles', '0006_auto_20190425_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='academic_class',
            name='dept_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpFiles.Academic_dept'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='class_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wpFiles.Academic_class'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='upload',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
